name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install zpm
      run: sudo npm install -g @zpmpkg/zpm@next
    - name: download dependencies
      run: sudo zpm
    - name: run cmake
      run: cmake .
    - name: build
      run: cmake --build .
